<Type Name="AsynchronousOperationException" FullName="System.IdentityModel.AsynchronousOperationException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="464231eca198784865eb03b63a2700ae613a0632" /><Meta Name="ms.sourcegitcommit" Value="c982ad9e10a242d90f1e631b5981570f9e5d9f34" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="zh-CN" /><Meta Name="ms.lasthandoff" Value="09/10/2020" /><Meta Name="ms.locfileid" Value="89916179" /></Metadata><TypeSignature Language="C#" Value="public class AsynchronousOperationException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AsynchronousOperationException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.IdentityModel.AsynchronousOperationException" />
  <TypeSignature Language="VB.NET" Value="Public Class AsynchronousOperationException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class AsynchronousOperationException : Exception" />
  <TypeSignature Language="F#" Value="type AsynchronousOperationException = class&#xA;    inherit Exception" />
  <AssemblyInfo>
    <AssemblyName>System.IdentityModel</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName Language="C#">[System.Serializable]</AttributeName>
      <AttributeName Language="F#">[&lt;System.Serializable&gt;]</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="53db4-101">异步操作发生错误时引发的异常。</span><span class="sxs-lookup"><span data-stu-id="53db4-101">The exception that is thrown when an error occurs during an asynchronous operation.</span></span></summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="53db4-102">初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-102">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="53db4-103">初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-103">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="53db4-104">此构造函数将新实例的 <xref:System.Exception.Message> 属性初始化为系统提供的错误描述消息。</span><span class="sxs-lookup"><span data-stu-id="53db4-104">This constructor initializes the <xref:System.Exception.Message> property of the new instance to a system-supplied message that describes the error.</span></span> <span data-ttu-id="53db4-105">此消息会考虑当前系统区域性。</span><span class="sxs-lookup"><span data-stu-id="53db4-105">This message takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="53db4-106">下表显示了新实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="53db4-106">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="53db4-107">Property</span><span class="sxs-lookup"><span data-stu-id="53db4-107">Property</span></span>|<span data-ttu-id="53db4-108">值</span><span class="sxs-lookup"><span data-stu-id="53db4-108">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="53db4-109">`null`.</span><span class="sxs-lookup"><span data-stu-id="53db4-109">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="53db4-110">本地化的错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="53db4-110">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException innerException" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException"><span data-ttu-id="53db4-111">导致当前异常的 <see cref="T:System.Exception" />。</span><span class="sxs-lookup"><span data-stu-id="53db4-111">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span></span> <span data-ttu-id="53db4-112">如果 <paramref name="innerException" /> 参数不为 <see langword="null" />，则当前异常将在处理内部异常的 <see langword="catch" /> 块中引发。</span><span class="sxs-lookup"><span data-stu-id="53db4-112">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="53db4-113">使用指定错误信息和对作为此异常原因的内部异常的引用来初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-113">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a system-supplied error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="53db4-114">因前一个异常而直接引发的异常应在 <xref:System.Exception.InnerException%2A> 属性中包含对前一个异常的引用。</span><span class="sxs-lookup"><span data-stu-id="53db4-114">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="53db4-115"><xref:System.Exception.InnerException%2A>属性返回传递到构造函数中的相同值。</span><span class="sxs-lookup"><span data-stu-id="53db4-115">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="53db4-116">下表显示了新实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="53db4-116">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="53db4-117">Property</span><span class="sxs-lookup"><span data-stu-id="53db4-117">Property</span></span>|<span data-ttu-id="53db4-118">“值”</span><span class="sxs-lookup"><span data-stu-id="53db4-118">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="53db4-119">内部异常引用。</span><span class="sxs-lookup"><span data-stu-id="53db4-119">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="53db4-120">系统提供的描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="53db4-120">A system-supplied message that describes the error.</span></span> <span data-ttu-id="53db4-121">此消息会考虑当前系统区域性。</span><span class="sxs-lookup"><span data-stu-id="53db4-121">This message takes into account the current system culture.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="53db4-122">解释异常原因的错误消息。</span><span class="sxs-lookup"><span data-stu-id="53db4-122">The error message that explains the reason for the exception.</span></span></param>
        <summary><span data-ttu-id="53db4-123">用指定的错误消息初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-123">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="53db4-124">此构造函数 <xref:System.Exception.Message%2A> 使用参数初始化新异常的属性 `message` 。</span><span class="sxs-lookup"><span data-stu-id="53db4-124">This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter.</span></span> <span data-ttu-id="53db4-125">`message` 的内容设计为易于理解。</span><span class="sxs-lookup"><span data-stu-id="53db4-125">The content of `message` is intended to be understood by humans.</span></span> <span data-ttu-id="53db4-126">此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。</span><span class="sxs-lookup"><span data-stu-id="53db4-126">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span></span>  
  
 <span data-ttu-id="53db4-127">下表显示了新实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="53db4-127">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="53db4-128">Property</span><span class="sxs-lookup"><span data-stu-id="53db4-128">Property</span></span>|<span data-ttu-id="53db4-129">值</span><span class="sxs-lookup"><span data-stu-id="53db4-129">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="53db4-130">`null`.</span><span class="sxs-lookup"><span data-stu-id="53db4-130">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="53db4-131">错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="53db4-131">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; AsynchronousOperationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="53db4-132">保留序列化对象数据的 <see cref="T:System.Runtime.Serialization.SerializationInfo" /> 对象。</span><span class="sxs-lookup"><span data-stu-id="53db4-132">A <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object that holds the serialized object data.</span></span></param>
        <param name="context"><span data-ttu-id="53db4-133"><see cref="T:System.Runtime.Serialization.StreamingContext" /> 对象，它包含有关源或目标的上下文信息。</span><span class="sxs-lookup"><span data-stu-id="53db4-133">A <see cref="T:System.Runtime.Serialization.StreamingContext" /> object that contains the contextual information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="53db4-134">用序列化数据初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-134">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with serialized data.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="53db4-135">在反序列化期间调用此构造函数以重新构造在流上传输的异常对象。</span><span class="sxs-lookup"><span data-stu-id="53db4-135">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string * Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="53db4-136">解释异常原因的错误消息。</span><span class="sxs-lookup"><span data-stu-id="53db4-136">The error message that explains the reason for the exception.</span></span></param>
        <param name="innerException"><span data-ttu-id="53db4-137">导致当前异常的 <see cref="T:System.Exception" />。</span><span class="sxs-lookup"><span data-stu-id="53db4-137">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span></span> <span data-ttu-id="53db4-138">如果 <paramref name="innerException" /> 参数不为 <see langword="null" />，则当前异常将在处理内部异常的 <see langword="catch" /> 块中引发。</span><span class="sxs-lookup"><span data-stu-id="53db4-138">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="53db4-139">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <see cref="T:System.IdentityModel.AsynchronousOperationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="53db4-139">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="53db4-140">因前一个异常而直接引发的异常应在 <xref:System.Exception.InnerException%2A> 属性中包含对前一个异常的引用。</span><span class="sxs-lookup"><span data-stu-id="53db4-140">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="53db4-141"><xref:System.Exception.InnerException%2A>属性返回传递到构造函数中的相同值。</span><span class="sxs-lookup"><span data-stu-id="53db4-141">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="53db4-142">下表显示了新实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="53db4-142">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="53db4-143">Property</span><span class="sxs-lookup"><span data-stu-id="53db4-143">Property</span></span>|<span data-ttu-id="53db4-144">“值”</span><span class="sxs-lookup"><span data-stu-id="53db4-144">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="53db4-145">内部异常引用。</span><span class="sxs-lookup"><span data-stu-id="53db4-145">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="53db4-146">错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="53db4-146">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>
