<Type Name="LinqDataSourceValidationException" FullName="System.Web.UI.WebControls.LinqDataSourceValidationException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="bfbee097cb2a9391e60fe196e358a6571af8e9ca" /><Meta Name="ms.sourcegitcommit" Value="11d168140aa8fade0768c2a9dde3e3bcacfdfb7d" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="zh-CN" /><Meta Name="ms.lasthandoff" Value="05/27/2020" /><Meta Name="ms.locfileid" Value="83962870" /></Metadata><TypeSignature Language="C#" Value="public class LinqDataSourceValidationException : Exception, System.Web.DynamicData.IDynamicValidatorException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit LinqDataSourceValidationException extends System.Exception implements class System.Runtime.Serialization.ISerializable, class System.Web.DynamicData.IDynamicValidatorException" />
  <TypeSignature Language="DocId" Value="T:System.Web.UI.WebControls.LinqDataSourceValidationException" />
  <TypeSignature Language="VB.NET" Value="Public Class LinqDataSourceValidationException&#xA;Inherits Exception&#xA;Implements IDynamicValidatorException" />
  <TypeSignature Language="C++ CLI" Value="public ref class LinqDataSourceValidationException : Exception, System::Web::DynamicData::IDynamicValidatorException" />
  <TypeSignature Language="F#" Value="type LinqDataSourceValidationException = class&#xA;    inherit Exception&#xA;    interface IDynamicValidatorException&#xA;    interface ISerializable" />
  <AssemblyInfo>
    <AssemblyName>System.Web.Extensions</AssemblyName>
    <AssemblyVersion>3.5.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces>
    <Interface>
      <InterfaceName>System.Runtime.Serialization.ISerializable</InterfaceName>
    </Interface>
    <Interface>
      <InterfaceName>System.Web.DynamicData.IDynamicValidatorException</InterfaceName>
    </Interface>
  </Interfaces>
  <Attributes>
    <Attribute>
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="eba1d-101">描述在 <see cref="T:System.Web.UI.WebControls.LinqDataSource" /> 控件插入、更新或删除值之前验证新值或修改后的值期间发生的异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-101">Describes an exception that occurred during validation of new or modified values before values are inserted, updated, or deleted by a <see cref="T:System.Web.UI.WebControls.LinqDataSource" /> control.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-102"><xref:System.Web.UI.WebControls.LinqDataSourceValidationException> 类包含类型转换和属性 setter 异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-102">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class contains type conversion and property setter exceptions.</span></span> <span data-ttu-id="eba1d-103">在验证过程中引发的所有异常都包含在 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> 集合中。</span><span class="sxs-lookup"><span data-stu-id="eba1d-103">All of the exceptions that are thrown during validation are contained in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection.</span></span> <span data-ttu-id="eba1d-104">可以通过遍历 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> 集合来检索每个验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-104">You can retrieve each validation exception by iterating through the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection.</span></span>  
  
 <span data-ttu-id="eba1d-105">通常会在 <xref:System.Web.UI.WebControls.LinqDataSource.Updating>、<xref:System.Web.UI.WebControls.LinqDataSource.Deleting>和 <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> 事件中处理异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-105">You typically handle exceptions in the <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, and <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> events.</span></span> <span data-ttu-id="eba1d-106">如果引发验证异常，则 <xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs>、<xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs>或 <xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs> 对象的 `Exception` 属性包含 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> 对象。</span><span class="sxs-lookup"><span data-stu-id="eba1d-106">If a validation exception is thrown, the `Exception` property of the <xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs>, <xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs>, or <xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs> object contains a <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> object.</span></span> <span data-ttu-id="eba1d-107">如果未引发异常，则 `Exception` 属性将包含 `null`。</span><span class="sxs-lookup"><span data-stu-id="eba1d-107">If no exception is thrown, the `Exception` property contains `null`.</span></span>  
  
 <span data-ttu-id="eba1d-108">若要处理验证异常，请为 <xref:System.Web.UI.WebControls.LinqDataSource.Updating>、<xref:System.Web.UI.WebControls.LinqDataSource.Deleting>或 <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> 事件创建处理程序。</span><span class="sxs-lookup"><span data-stu-id="eba1d-108">To handle validation exceptions, create a handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating>, <xref:System.Web.UI.WebControls.LinqDataSource.Deleting>, or <xref:System.Web.UI.WebControls.LinqDataSource.Inserting> event.</span></span> <span data-ttu-id="eba1d-109">在事件处理程序中，检查事件参数类的 `Exception` 属性是否包含除 `null`之外的值。</span><span class="sxs-lookup"><span data-stu-id="eba1d-109">In the event handler, check whether the `Exception` property of the event argument class contains a value other than `null`.</span></span> <span data-ttu-id="eba1d-110">如果 `Exception` 属性不为 null，则会引发一个或多个验证异常，你可以在 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> 属性中检索每个验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-110">If the `Exception` property is not null, one or more validation exceptions were thrown and you can retrieve each validation exception in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> property.</span></span>  
  
 <span data-ttu-id="eba1d-111">如果值与属性的类型不匹配，则会发生验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-111">A validation exception can occur if a value does not match the type of the property.</span></span> <span data-ttu-id="eba1d-112">例如，尝试使用非数字字符更新整数属性会导致验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-112">For example, trying to update an integer property by using non-numeric characters causes a validation exception.</span></span> <span data-ttu-id="eba1d-113">LINQ to SQL 类还可以包含自定义验证条件，这些条件可确保属性包含的值在预期范围或模式内。</span><span class="sxs-lookup"><span data-stu-id="eba1d-113">A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="eba1d-114">下面的示例演示了 <xref:System.Web.UI.WebControls.LinqDataSource.Updating> 事件的事件处理程序。</span><span class="sxs-lookup"><span data-stu-id="eba1d-114">The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event.</span></span> <span data-ttu-id="eba1d-115">它通过使用 <xref:System.Web.UI.WebControls.Label> 控件来显示任何验证异常消息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-115">It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.</span></span>  
  
```vb  
Protected Sub LinqDataSource_Updating(ByVal sender As Object, _  
        ByVal e As LinqDataSourceUpdateEventArgs)  
    If (e.Exception IsNot Nothing) Then  
        For Each innerException As KeyValuePair(Of String, Exception) _  
               In e.Exception.InnerExceptions  
            Label1.Text &= innerException.Key & ": " & _  
                innerException.Value.Message & "<br />"  
        Next  
        e.ExceptionHandled = True  
    End If  
End Sub  
```  
  
```csharp  
protected void LinqDataSource_Updating(object sender,   
        LinqDataSourceUpdateEventArgs e)  
{  
    if (e.Exception != null)  
    {  
        foreach (KeyValuePair<string, Exception> innerException in   
             e.Exception.InnerExceptions)  
        {  
        Label1.Text += innerException.Key + ": " +   
            innerException.Value.Message + "<br />";  
        }  
        e.ExceptionHandled = true;  
    }  
}  
```  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="eba1d-116">初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-116">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="eba1d-117">使用说明错误的系统提供的消息初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-117">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a system-supplied message that describes the error.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-118">系统提供的描述错误的消息将考虑当前系统区域性。</span><span class="sxs-lookup"><span data-stu-id="eba1d-118">The system-supplied message that describes the error takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="eba1d-119">下表显示 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> 类的实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="eba1d-119">The following table shows the initial property values for an instance of the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class.</span></span>  
  
|<span data-ttu-id="eba1d-120">属性</span><span class="sxs-lookup"><span data-stu-id="eba1d-120">Property</span></span>|<span data-ttu-id="eba1d-121">值</span><span class="sxs-lookup"><span data-stu-id="eba1d-121">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="eba1d-122">`null` 列中的一个值匹配。</span><span class="sxs-lookup"><span data-stu-id="eba1d-122">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="eba1d-123">系统提供的本地化说明。</span><span class="sxs-lookup"><span data-stu-id="eba1d-123">A system-supplied localized description.</span></span>|  
  
 ]]></format>
        </remarks>
        <related type="Article" href="/dotnet/standard/exceptions/"><span data-ttu-id="eba1d-124">处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="eba1d-124">Handling and Throwing Exceptions</span></span></related>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Web.UI.WebControls.LinqDataSourceValidationException : string -&gt; System.Web.UI.WebControls.LinqDataSourceValidationException" Usage="new System.Web.UI.WebControls.LinqDataSourceValidationException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="eba1d-125">用于描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-125">The message that describes the error.</span></span></param>
        <summary><span data-ttu-id="eba1d-126">使用说明错误的指定消息初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-126">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified message that describes the error.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-127">下表显示 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> 类的实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="eba1d-127">The following table shows the initial property values for an instance of the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException> class.</span></span>  
  
|<span data-ttu-id="eba1d-128">属性</span><span class="sxs-lookup"><span data-stu-id="eba1d-128">Property</span></span>|<span data-ttu-id="eba1d-129">值</span><span class="sxs-lookup"><span data-stu-id="eba1d-129">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="eba1d-130">`null` 列中的一个值匹配。</span><span class="sxs-lookup"><span data-stu-id="eba1d-130">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="eba1d-131">`message` 中指定的错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="eba1d-131">The error message string specified in `message`.</span></span>|  
  
 ]]></format>
        </remarks>
        <related type="Article" href="/dotnet/standard/exceptions/"><span data-ttu-id="eba1d-132">处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="eba1d-132">Handling and Throwing Exceptions</span></span></related>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected LinqDataSourceValidationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; LinqDataSourceValidationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.Web.UI.WebControls.LinqDataSourceValidationException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.Web.UI.WebControls.LinqDataSourceValidationException" Usage="new System.Web.UI.WebControls.LinqDataSourceValidationException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="eba1d-133">包含序列化对象数据的对象。</span><span class="sxs-lookup"><span data-stu-id="eba1d-133">The object that holds the serialized object data.</span></span></param>
        <param name="context"><span data-ttu-id="eba1d-134">有关源或目标的上下文信息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-134">Context information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="eba1d-135">使用序列化数据初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-135">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with serialized data.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-136">在反序列化过程中调用此构造函数来重建通过流传输的异常对象。</span><span class="sxs-lookup"><span data-stu-id="eba1d-136">This constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message, System.Collections.Generic.IDictionary&lt;string,Exception&gt; innerExceptions);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Collections.Generic.IDictionary`2&lt;string, class System.Exception&gt; innerExceptions) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerExceptions As IDictionary(Of String, Exception))" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message, System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ innerExceptions);" />
      <MemberSignature Language="F#" Value="new System.Web.UI.WebControls.LinqDataSourceValidationException : string * System.Collections.Generic.IDictionary&lt;string, Exception&gt; -&gt; System.Web.UI.WebControls.LinqDataSourceValidationException" Usage="new System.Web.UI.WebControls.LinqDataSourceValidationException (message, innerExceptions)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerExceptions" Type="System.Collections.Generic.IDictionary&lt;System.String,System.Exception&gt;" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="eba1d-137">用于描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-137">The message that describes the error.</span></span></param>
        <param name="innerExceptions"><span data-ttu-id="eba1d-138">验证异常的集合。</span><span class="sxs-lookup"><span data-stu-id="eba1d-138">The collection of validation exceptions.</span></span></param>
        <summary><span data-ttu-id="eba1d-139">使用描述错误的指定消息和对内部异常的引用集合来初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-139">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified message that describes the error, and a collection of references to inner exceptions.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public LinqDataSourceValidationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; LinqDataSourceValidationException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.Web.UI.WebControls.LinqDataSourceValidationException : string * Exception -&gt; System.Web.UI.WebControls.LinqDataSourceValidationException" Usage="new System.Web.UI.WebControls.LinqDataSourceValidationException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="eba1d-140">用于描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-140">The message that describes the error.</span></span></param>
        <param name="innerException"><span data-ttu-id="eba1d-141">引起当前异常的异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-141">The exception that is the cause of the current exception.</span></span></param>
        <summary><span data-ttu-id="eba1d-142">使用指定的错误消息和对内部异常的引用初始化 <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="eba1d-142">Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /> class with a specified error message and a reference to the inner exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-143">通常不会使用此构造函数，因为验证异常存储在 <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> 属性中，而不是 <xref:System.Exception.InnerException%2A> 属性中。</span><span class="sxs-lookup"><span data-stu-id="eba1d-143">You typically will not use this constructor because validation exceptions are stored in the <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> property, not the <xref:System.Exception.InnerException%2A> property.</span></span>  
  
 ]]></format>
        </remarks>
        <related type="Article" href="/dotnet/standard/exceptions/"><span data-ttu-id="eba1d-144">处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="eba1d-144">Handling and Throwing Exceptions</span></span></related>
      </Docs>
    </Member>
    <Member MemberName="GetObjectData">
      <MemberSignature Language="C#" Value="public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance void GetObjectData(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Sub GetObjectData (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; override void GetObjectData(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="override this.GetObjectData : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; unit" Usage="linqDataSourceValidationException.GetObjectData (info, context)" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8">
          <AttributeName>System.Security.SecurityCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Void</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="eba1d-145">一个对象，保存有关所引发异常的序列化对象数据。</span><span class="sxs-lookup"><span data-stu-id="eba1d-145">The object that holds the serialized object data for the exception that is being thrown.</span></span></param>
        <param name="context"><span data-ttu-id="eba1d-146">有关源或目标的上下文信息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-146">Context information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="eba1d-147">获取关于异常的信息并将其添加到 <see cref="T:System.Runtime.Serialization.SerializationInfo" /> 对象。</span><span class="sxs-lookup"><span data-stu-id="eba1d-147">Gets information about the exception and adds it to the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-148"><xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A> 方法将有关异常的信息添加到作为序列化目标的 <xref:System.Runtime.Serialization.SerializationInfo> 对象中。</span><span class="sxs-lookup"><span data-stu-id="eba1d-148">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A> method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization.</span></span> <span data-ttu-id="eba1d-149">在反序列化期间，将从通过流传输的 <xref:System.Runtime.Serialization.SerializationInfo> 重建异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-149">During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="InnerExceptions">
      <MemberSignature Language="C#" Value="public System.Collections.Generic.IDictionary&lt;string,Exception&gt; InnerExceptions { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Collections.Generic.IDictionary`2&lt;string, class System.Exception&gt; InnerExceptions" />
      <MemberSignature Language="DocId" Value="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property InnerExceptions As IDictionary(Of String, Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ InnerExceptions { System::Collections::Generic::IDictionary&lt;System::String ^, Exception ^&gt; ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.InnerExceptions : System.Collections.Generic.IDictionary&lt;string, Exception&gt;" Usage="System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Web.DynamicData.IDynamicValidatorException.InnerExceptions</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Web.Extensions</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Collections.Generic.IDictionary&lt;System.String,System.Exception&gt;</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="eba1d-150">获取在验证新值或修改后的值期间发生的一个或多个异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-150">Gets one or more exceptions that occurred when new or modified data was being validated.</span></span></summary>
        <value><span data-ttu-id="eba1d-151">一个包含异常的集合。</span><span class="sxs-lookup"><span data-stu-id="eba1d-151">A collection that contains the exceptions.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="eba1d-152"><xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> 集合包含在更新、插入或删除操作之前在数据验证期间引发的所有验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-152">The <xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A> collection contains all the validation exceptions that were thrown during data validation before an update, insert, or delete operation.</span></span> <span data-ttu-id="eba1d-153">如果值与属性的类型不匹配，则会发生验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-153">A validation exception can occur if a value does not match the type of the property.</span></span> <span data-ttu-id="eba1d-154">例如，如果你尝试使用非数字字符更新整数属性，则会引发验证异常。</span><span class="sxs-lookup"><span data-stu-id="eba1d-154">For example, if you try to update an integer property by using non-numeric characters, a validation exception is thrown.</span></span> <span data-ttu-id="eba1d-155">LINQ to SQL 类还可以包含自定义验证条件，这些条件可确保属性包含的值在预期范围或模式内。</span><span class="sxs-lookup"><span data-stu-id="eba1d-155">A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="eba1d-156">下面的示例演示了 <xref:System.Web.UI.WebControls.LinqDataSource.Updating> 事件的事件处理程序。</span><span class="sxs-lookup"><span data-stu-id="eba1d-156">The following example shows an event handler for the <xref:System.Web.UI.WebControls.LinqDataSource.Updating> event.</span></span> <span data-ttu-id="eba1d-157">它通过使用 <xref:System.Web.UI.WebControls.Label> 控件来显示任何验证异常消息。</span><span class="sxs-lookup"><span data-stu-id="eba1d-157">It displays any validation exception messages by using a <xref:System.Web.UI.WebControls.Label> control.</span></span>  
  
```vb  
Protected Sub LinqDataSource_Updating(ByVal sender As Object, _  
        ByVal e As LinqDataSourceUpdateEventArgs)  
    If (e.Exception IsNot Nothing) Then  
        For Each innerException As KeyValuePair(Of String, Exception) _  
                In e.Exception.InnerExceptions  
          Label1.Text &= innerException.Key & ": " & _   
                  innerException.Value.Message & "<br />"  
        Next  
        e.ExceptionHandled = True  
    End If  
End Sub  
```  
  
```csharp  
protected void LinqDataSource_Updating(object sender,   
        LinqDataSourceUpdateEventArgs e)   
{  
    if (e.Exception != null)  
    {  
        foreach (KeyValuePair<string, Exception> innerException in   
            e.Exception.InnerExceptions)  
        {  
            Label1.Text += innerException.Key + ": " +   
                innerException.Message + "<br />";  
        }  
        e.ExceptionHandled = true;  
    }  
}  
```  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>
