<Type Name="ServerException" FullName="System.Runtime.Remoting.ServerException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="1e5a3b3fea44356298c675f34231de1b26aaecbe" /><Meta Name="ms.sourcegitcommit" Value="11d168140aa8fade0768c2a9dde3e3bcacfdfb7d" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="zh-CN" /><Meta Name="ms.lasthandoff" Value="05/27/2020" /><Meta Name="ms.locfileid" Value="83955550" /></Metadata><TypeSignature Language="C#" Value="public class ServerException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit ServerException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.Remoting.ServerException" />
  <TypeSignature Language="VB.NET" Value="Public Class ServerException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class ServerException : SystemException" />
  <TypeSignature Language="F#" Value="type ServerException = class&#xA;    inherit SystemException" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="0f260-101">当客户端连接到无法引发异常的非 .NET Framework 应用程序时，则引发该异常，以向客户端传达错误。</span><span class="sxs-lookup"><span data-stu-id="0f260-101">The exception that is thrown to communicate errors to the client when the client connects to non-.NET Framework applications that cannot throw exceptions.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="0f260-102"><xref:System.Runtime.Remoting.ServerException> 使用值为0x8013150E 的 HRESULT COR_E_SERVER。</span><span class="sxs-lookup"><span data-stu-id="0f260-102"><xref:System.Runtime.Remoting.ServerException> uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</span></span>  
  
 <span data-ttu-id="0f260-103"><xref:System.Runtime.Remoting.ServerException> 使用默认的 <xref:System.Object.Equals%2A> 实现，该实现支持引用相等性。</span><span class="sxs-lookup"><span data-stu-id="0f260-103"><xref:System.Runtime.Remoting.ServerException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.</span></span>  
  
 <span data-ttu-id="0f260-104">有关实例的初始属性值的列表<xref:System.Runtime.Remoting.ServerException>，请参阅<xref:System.Runtime.Remoting.ServerException>构造函数。</span><span class="sxs-lookup"><span data-stu-id="0f260-104">For a list of initial property values for an instance of <xref:System.Runtime.Remoting.ServerException>, see the <xref:System.Runtime.Remoting.ServerException> constructors.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Exception" />
    <related type="Article" href="/dotnet/standard/exceptions/"><span data-ttu-id="0f260-105">在 .NET 中处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="0f260-105">Handling and throwing exceptions in .NET</span></span></related>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="0f260-106">初始化 <see cref="T:System.Runtime.Remoting.ServerException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="0f260-106">Initializes a new instance of the <see cref="T:System.Runtime.Remoting.ServerException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ServerException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.Remoting.ServerException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; ServerException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="0f260-107">使用默认属性初始化 <see cref="T:System.Runtime.Remoting.ServerException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="0f260-107">Initializes a new instance of the <see cref="T:System.Runtime.Remoting.ServerException" /> class with default properties.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="0f260-108"><xref:System.Runtime.Remoting.ServerException> 继承自 <xref:System.SystemException> 类。</span><span class="sxs-lookup"><span data-stu-id="0f260-108"><xref:System.Runtime.Remoting.ServerException> inherits from the <xref:System.SystemException> class.</span></span> <span data-ttu-id="0f260-109">下表显示了 <xref:System.Runtime.Remoting.ServerException> 类的实例的初始属性值：</span><span class="sxs-lookup"><span data-stu-id="0f260-109">The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.ServerException> class:</span></span>  
  
|<span data-ttu-id="0f260-110">properties</span><span class="sxs-lookup"><span data-stu-id="0f260-110">Property</span></span>|<span data-ttu-id="0f260-111">值</span><span class="sxs-lookup"><span data-stu-id="0f260-111">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="0f260-112">空字符串（""）</span><span class="sxs-lookup"><span data-stu-id="0f260-112">The empty string ("")</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ServerException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.Remoting.ServerException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; ServerException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Runtime.Remoting.ServerException : string -&gt; System.Runtime.Remoting.ServerException" Usage="new System.Runtime.Remoting.ServerException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="0f260-113">描述该异常的消息</span><span class="sxs-lookup"><span data-stu-id="0f260-113">The message that describes the exception</span></span></param>
        <summary><span data-ttu-id="0f260-114">用指定的消息初始化 <see cref="T:System.Runtime.Remoting.ServerException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="0f260-114">Initializes a new instance of the <see cref="T:System.Runtime.Remoting.ServerException" /> class with a specified message.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="0f260-115"><xref:System.Runtime.Remoting.ServerException> 继承自 <xref:System.SystemException> 类。</span><span class="sxs-lookup"><span data-stu-id="0f260-115"><xref:System.Runtime.Remoting.ServerException> inherits from the <xref:System.SystemException> class.</span></span> <span data-ttu-id="0f260-116">下表显示了 <xref:System.Runtime.Remoting.ServerException> 类的实例的初始属性值：</span><span class="sxs-lookup"><span data-stu-id="0f260-116">The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.ServerException> class:</span></span>  
  
|<span data-ttu-id="0f260-117">属性类型</span><span class="sxs-lookup"><span data-stu-id="0f260-117">Property Type</span></span>|<span data-ttu-id="0f260-118">条件</span><span class="sxs-lookup"><span data-stu-id="0f260-118">Condition</span></span>|  
|-------------------|---------------|  
|<xref:System.Exception.InnerException%2A>|`null`|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="0f260-119">`message` 字符串</span><span class="sxs-lookup"><span data-stu-id="0f260-119">The `message` string</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public ServerException (string message, Exception InnerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception InnerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, InnerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; ServerException(System::String ^ message, Exception ^ InnerException);" />
      <MemberSignature Language="F#" Value="new System.Runtime.Remoting.ServerException : string * Exception -&gt; System.Runtime.Remoting.ServerException" Usage="new System.Runtime.Remoting.ServerException (message, InnerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="InnerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="0f260-120">用于解释异常原因的错误消息。</span><span class="sxs-lookup"><span data-stu-id="0f260-120">The error message that explains the reason for the exception.</span></span></param>
        <param name="InnerException"><span data-ttu-id="0f260-121">导致当前异常的异常。</span><span class="sxs-lookup"><span data-stu-id="0f260-121">The exception that is the cause of the current exception.</span></span> <span data-ttu-id="0f260-122">如果 <paramref name="InnerException" /> 参数不为 <see langword="null" />，则当前异常将在处理内部异常的 <see langword="catch" /> 块中引发。</span><span class="sxs-lookup"><span data-stu-id="0f260-122">If the <paramref name="InnerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="0f260-123">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <see cref="T:System.Runtime.Remoting.ServerException" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="0f260-123">Initializes a new instance of the <see cref="T:System.Runtime.Remoting.ServerException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="0f260-124">作为前一个异常的直接结果引发的异常应在 <xref:System.Exception.InnerException%2A> 属性中包含对前一个异常的引用。</span><span class="sxs-lookup"><span data-stu-id="0f260-124">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="0f260-125"><xref:System.Exception.InnerException%2A> 属性将返回传递给构造函数的同一值；如果 <xref:System.Exception.InnerException%2A> 属性不向构造函数提供内部异常值，则返回 `null`。</span><span class="sxs-lookup"><span data-stu-id="0f260-125">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="0f260-126">下表显示了 <xref:System.Runtime.Remoting.ServerException> 类的实例的初始属性值：</span><span class="sxs-lookup"><span data-stu-id="0f260-126">The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.ServerException> class:</span></span>  
  
|<span data-ttu-id="0f260-127">properties</span><span class="sxs-lookup"><span data-stu-id="0f260-127">Property</span></span>|<span data-ttu-id="0f260-128">值</span><span class="sxs-lookup"><span data-stu-id="0f260-128">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="0f260-129">内部异常引用</span><span class="sxs-lookup"><span data-stu-id="0f260-129">The inner exception reference</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="0f260-130">错误消息字符串</span><span class="sxs-lookup"><span data-stu-id="0f260-130">The error message string</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <related type="Article" href="/dotnet/standard/exceptions/"><span data-ttu-id="0f260-131">在 .NET 中处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="0f260-131">Handling and throwing exceptions in .NET</span></span></related>
      </Docs>
    </Member>
  </Members>
</Type>
